### ISSUE TITLE
localized text is not shown on local build

### ISSUE THREAD

**Issue by enricogallesio** [zankhq/astros#26]
Hello
I successfully deployed a newly cloned Astros on netlify, it works correctly. However, when I build that same repo locally with "npm run build" and then "npm run preview" the all the localized texts are not shown, instead just placeholders like "hero.title" or "hero.main_button_text" are displayed. Same with "npm run dev".

![sshot](https://github.com/zankhq/astros/assets/1489167/b299b77b-a05a-4ff1-a013-5e316dc6f385)

I'm not sure what I'm doing wrong. I tried using the same node and npm versions as netlify but my local build keeps failing at showing the translated text. 

Logs and warning look the same on netlify and in local.

Could you please help me troubleshooting this issue?
Thank you very much

**Comment by zanhk** [comment]
Hi @enricogallesio,

I was not able to reproduce the bug, are you using windows or mac?

Do you see see any particular warning/error on the console?

---

Anyway I m planning to change the localization system sometime in the next weeks as [astro-i18next](https://github.com/yassinedoghri/astro-i18next) doesn't seem to be maintained anymore.

I think [astro-i18n-aut](https://github.com/jlarmstrongiv/astro-i18n-aut) use a better approach for localization.

If you want you may try to look at how i have implemented astro-i18n-aut on the astro-starter template https://github.com/zankhq/astro-starter.

But essentially:

- remove `astro-i18next.config.mjs` file
- remove astroI18next from `astro.config.mjs`
- remove the package `astro-i18next`
- install `astro-i18n-aut` and see how i implemented it on astro-starter https://github.com/zankhq/astro-starter/tree/main/src/locales, https://github.com/zankhq/astro-starter/blob/main/src/utils/t.ts

**Comment by enricogallesio** [comment]
Hi
I'm on linux, however I've found a similar problem with astro-18next mentioned [here](https://github.com/yassinedoghri/astro-i18next/issues/103) happening on other OS.
I haven't figured out this yet, but in the meantime I'll try with astro-i18n-aut which seems more promising.
Thank you very much for your help!

**Comment by enricogallesio** [comment]
I've found the problem that caused the issue. Oddly enough, the issue was caused by the presence of a white space in the local path of the project. *facepalm*

White space removed, issue solved.
Thank you again!

**Comment by Parthvsquare** [comment]
hey @enricogallesio what did you change? i too have same issue but in macos

**Comment by enricogallesio** [comment]
> hey @enricogallesio what did you change? i too have same issue but in macos

Not sure if it's the same bug, I've just removed a white space from the local project path of directories.

I'm pretty sure this big can be caused by a missing space or special characters escaping in the project path, but this may not be the only way to trigger this issue

**Comment by Parthvsquare** [comment]
> Not sure if it's the same bug, I've just removed a white space from the local project path of directories.

noob question, which local project path? which config?

**Comment by enricogallesio** [comment]
> > Not sure if it's the same bug, I've just removed a white space from the local project path of directories.
> 
> noob question, which local project path? which config?

For local path I mean the path of directories (folders) on your local system. For example mine was something like:
eg. /home/myname/personal project/astros
as you can see there is a empty space in the "personal project" folder name. When I simply removed that space in the folder name everything worked again.
eg. /home/myname/personalproject/astros

I'm not sure where is the bug, but in my case this simple workaround fixed the issue. I also should admit that spaces in folders names are not generally recommended. And that's for a reason...

**Comment by Parthvsquare** [comment]
This surprisingly worked :)
