### ISSUE TITLE
Too slow for mobile

### ISSUE THREAD

**Issue by ishandutta2007** [zankhq/astros#31]
Performance is Great for desktop but too slow for mobile.

**Mobile:**

![Screenshot 2023-10-17 at 6 13 31 PM](https://github.com/zankhq/astros/assets/2527354/7f7291a1-0b5b-4a34-902c-05dddc803430)

**Desktop:**

![Screenshot 2023-10-17 at 6 13 59 PM](https://github.com/zankhq/astros/assets/2527354/7904c2a1-4f19-4eb8-b613-034d2e343d2f)

Check yourself at : https://pagespeed.web.dev/

**Comment by zanhk** [comment]
Hi @ishandutta2007, i just checked and i got consistend 99 on mobile (run 5 times)

![image](https://github.com/zankhq/astros/assets/17980844/2a36da05-4169-4994-9a65-433590b36724)


Used to be 100 tho, i will check how to optimize to get the missing 1%

---

Probably at the moment you checked there was some problems with cloudflare infrastructure

**Comment by zanhk** [comment]
![image](https://github.com/zankhq/astros/assets/17980844/15d69d3a-f709-4606-a19c-58aca4818122)

**Comment by ishandutta2007** [comment]
It now it seems fine. If I remember I also tested multiple times and didnt come close to 90s if I remember. Maybe it had a issue with hosting.
