### ISSUE TITLE
i18n isn't working properly

### ISSUE THREAD

**Issue by wechselgeld** [zankhq/astros#36]
Hey! I've downloaded the template and installed all necessary dependencies. However, upon running the project with `npm run dev`, the language strings show their fallback form, like you can see here: 
![image](https://github.com/zankhq/astros/assets/38156742/47afda58-a79b-4987-864b-37c699b5ace1)

Me and some others attempted to locate the mistake, but were unsuccessful.

**Comment by zanhk** [comment]
Hi, try check out https://github.com/zankhq/astros/issues/26

The solution for @enricogallesio was to remove empty spaces from the path of the project folder

**Comment by wechselgeld** [comment]
Thank you for answering that fast! Surprisingly, that worked.
