### ISSUE TITLE
Cloudflare Pages deployment failing

### ISSUE THREAD

**Issue by arunthachi** [zankhq/astros#43]
Hi - I am deploying the repo as is into Cloudflare Pages, and I am getting the below error. But in my local it is running fine. 

<pre class="c_ki c_bv c_iw c_op c_on c_oo c_db c_su c_sv c_sw c_sx c_hp c_hq c_sg c_bx c_sy" style="box-sizing: border-box; border-radius: 0px; color: rgb(49, 49, 49); display: block; font-size: 12px; margin: 0px; overflow: auto; padding: 16px 32px; width: 837px; background-color: rgb(242, 242, 242); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(217, 217, 217); border-image: none; font-family: monaco, courier, monospace; height: 500px; caret-color: rgb(49, 49, 49); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">
19:21:47.352 | Executing user command: npm run build
-- | --
19:21:48.192 |  
19:21:48.207 | > astros@1.0.1 build
19:21:48.207 | > astro build
19:21:48.207 |  
19:21:50.041 | 12:21:50 AM [vite] Pre-transform error: Failed to load url hast-util-to-string (resolved id: hast-util-to-string) in /opt/buildhome/repo/plugins/rehype-autolink-config.ts. Does the file exist?
19:21:50.042 | 12:21:50 AM [vite] Pre-transform error: Failed to load url hastscript (resolved id: hastscript) in /opt/buildhome/repo/plugins/rehype-autolink-config.ts. Does the file exist?
19:21:50.055 | 12:21:50 AM [vite] Error when evaluating SSR module /plugins/rehype-autolink-config.ts: failed to import "hast-util-to-string"
19:21:50.055 | \|- Error: Cannot find module 'hast-util-to-string' imported from '/opt/buildhome/repo/plugins/rehype-autolink-config.ts'
19:21:50.056 | at nodeImport (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50234:25)
19:21:50.056 | at ssrImport (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50141:30)
19:21:50.056 | at eval (/opt/buildhome/repo/plugins/rehype-autolink-config.ts:3:50)
19:21:50.056 | at instantiateModule (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50203:15)
19:21:50.056 |  
19:21:50.056 | 12:21:50 AM [vite] Error when evaluating SSR module /opt/buildhome/repo/astro.config.mjs: failed to import "/plugins/rehype-autolink-config.ts"
19:21:50.056 | \|- Error: Cannot find module 'hast-util-to-string' imported from '/opt/buildhome/repo/plugins/rehype-autolink-config.ts'
19:21:50.056 | at nodeImport (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50234:25)
19:21:50.057 | at ssrImport (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50141:30)
19:21:50.057 | at eval (/opt/buildhome/repo/plugins/rehype-autolink-config.ts:3:50)
19:21:50.057 | at instantiateModule (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50203:15)
19:21:50.057 |  
19:21:50.057 | 12:21:50 AM [vite] Pre-transform error: Failed to load url html-escaper (resolved id: html-escaper) in /opt/buildhome/repo/plugins/rehype-autolink-config.ts. Does the file exist?
19:21:50.057 | [astro] Unable to load your Astro config
19:21:50.057 |  
19:21:50.515 | Cannot find module 'hast-util-to-string' imported from '/opt/buildhome/repo/plugins/rehype-autolink-config.ts'
19:21:50.515 | Stack trace:
19:21:50.515 | at nodeImport (file:///opt/buildhome/repo/node_modules/.pnpm/vite@5.0.7/node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:50234:25)
19:21:50.516 | at eval (/opt/buildhome/repo/plugins/rehype-autolink-config.ts:3:50)
19:21:50.679 | Failed: Error while executing user command. Exited with error code: 1
19:21:50.688 | Failed: build command exited with code: 1
19:21:51.659 | Failed: error occurred while running build command

</pre><div class="c_dh c_di c_d" style="box-sizing: border-box; display: flex; padding-top: 32px; padding-bottom: 32px; caret-color: rgb(49, 49, 49); color: rgb(49, 49, 49); font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"></div>

**Comment by zanhk** [comment]
Hi @arunthachi sorry i missed this issue, does the problem still persist?

**Comment by zanhk** [comment]
Closing as no updates
