### ISSUE TITLE
[WARN] [vite] The glob option "as" has been deprecated...

### ISSUE THREAD

**Issue by shanerobinson** [zankhq/astros#46]
I’m getting the following error in the terminal, working locally, as soon as the browser reloads after a file change: 

```
[WARN] [vite] The glob option "as" has been deprecated in favour of "query". Please update `as: 'raw'` to `query: '?raw', import: 'default'`.
```

Then no file changes will fire a browser reload. And even if I save changes in a file, forcing refresh in the browser won't show the file update. 

I use Brave but thought it might be a browser issue so tested in Firefox, Chrome, and Safari with same results. 

I have ZERO experience with Vite and have done extensive searches looking for the fix before posting here.

**Comment by zanhk** [comment]
IHi,  was not able to reproduce the problem, anyway I m planning to upgrade all packages as some are different version behind so I hope it will fix this problem as well

**Comment by zanhk** [comment]
I upgraded all dependencies, can you check if the error still persist on your side?
